# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 17:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamwork', 'load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedtime',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamwork.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='loggedtime',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamwork.Event'),
        ),
    ]
