# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0001_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='event', max_length=255),
        ),
    ]
