# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0003_auto_20161006_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DurationField()),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teamwork.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.AddField(
            model_name='loggedtime',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Project'),
        ),
        migrations.AddField(
            model_name='loggedtime',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Student'),
        ),
    ]
