# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0004_auto_20161007_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My task', max_length=255)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
