# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teamwork.Student'),
            preserve_default=False,
        ),
    ]
